use crate::errors::ProbeRunnerError;
use style_scraper_core::model::raw::RawFacts;

#[derive(Debug, Clone)]
pub struct CaptureConfig {
    pub url: String,
    pub viewport: String,
    pub viewports: Vec<String>,
    pub color_scheme: String,
    pub states: Vec<String>,
    pub include_screenshots: bool,
    pub screenshot: String,
    pub wait: String,
    pub wait_for_selector: Option<String>,
    pub timeout_ms: u64,
    pub navigation_timeout_ms: u64,
    pub capture_timeout_ms: u64,
    pub stability_window_ms: u64,
    pub max_stability_wait_ms: u64,
    pub ignore_networkidle_timeout: bool,
    pub capture_on_timeout: bool,
    pub strict_capture: bool,
    pub safe_capture: bool,
    pub resource_budget: String,
    pub block_third_party: bool,
    pub block_analytics: bool,
    pub block_media: bool,
    pub block_fonts: bool,
    pub block_images: bool,
    pub allow_active: bool,
    pub click_selector: Option<String>,
    pub auth_state: Option<String>,
    pub screenshot_dir: Option<String>,
    pub artifact_dir: Option<String>,
    pub keep_artifacts: bool,
    pub redact_text: bool,
    pub hash_text: bool,
    pub include_text: bool,
    pub redact_attributes: bool,
    pub redact_images: bool,
    pub safe_interactions: bool,
    pub no_click: bool,
    pub no_form_submit: bool,
    pub auto_install_deps: bool,
    pub deps_dir: Option<String>,
    pub playwright_browser: String,
}

impl Default for CaptureConfig {
    fn default() -> Self {
        Self {
            url: String::new(),
            viewport: "1440x900".to_string(),
            viewports: Vec::new(),
            color_scheme: "light".to_string(),
            states: Vec::new(),
            include_screenshots: false,
            screenshot: "viewport".to_string(),
            wait: "auto".to_string(),
            wait_for_selector: None,
            timeout_ms: 30_000,
            navigation_timeout_ms: 15_000,
            capture_timeout_ms: 30_000,
            stability_window_ms: 500,
            max_stability_wait_ms: 5_000,
            ignore_networkidle_timeout: true,
            capture_on_timeout: true,
            strict_capture: false,
            safe_capture: false,
            resource_budget: "balanced".to_string(),
            block_third_party: false,
            block_analytics: false,
            block_media: false,
            block_fonts: false,
            block_images: false,
            allow_active: false,
            click_selector: None,
            auth_state: None,
            screenshot_dir: None,
            artifact_dir: Some(".style-scraper/artifacts".to_string()),
            keep_artifacts: false,
            redact_text: false,
            hash_text: true,
            include_text: false,
            redact_attributes: false,
            redact_images: false,
            safe_interactions: true,
            no_click: true,
            no_form_submit: true,
            auto_install_deps: true,
            deps_dir: Some(".style-scraper/deps".to_string()),
            playwright_browser: "chromium".to_string(),
        }
    }
}

pub trait ProbeRunner {
    fn capture(&self, config: &CaptureConfig) -> Result<RawFacts, ProbeRunnerError>;
}
